### ISSUE TITLE
(SPRINT GOAL) Redesign Touring Asset

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#147]
Redesigning the road trip planner (https://www.visitscotland.com/travel-planning/getting-around/driving/route-planner/) to better reflect our sustainability goals. 

**Requirements** 
- Must be a map 
- Must include multiple routes 
- Must include multiple ways of transport and promote alternatives to car travel 

**Tasks** 

- [x] Familiarise ourselves with current asset 
- [x] Familiarise ourselves with work done by Abigail and Nikki (https://miro.com/app/board/uXjVMrAxW6s=/?share_link_id=47452636896) 
- [x] Kick-off meeting to determine what we want this map to achieve (community engagement, define parameters of what we're going to do, do we need to add anything/remove anything, how will we align with new brand)
- [x] Need to determine what routes/trails we have and what we want to include 
- Need a list/database of all the trails there are 
- There are STB routes advertised up North, but what are they? 
- Start off by including what is currently there, but can also be cycled/walked 
- [ ] Create lo-fi wireframe of new design 
- [x] Come up with ideas for how we will build the new map 
- [x] Determine if it's possible to map a line of a route (i.e., rough road layout as opposed to start and end points only) 
- [x] Determine how we want to show the stops on the map (link to DMS listings or itineraries or other approach?)
- [ ] Test the current asset to find out user's thoughts 
- [ ] Decide what to call it 
- [ ] Keyword research to inform name of asset 
- [x] Ideas for future iterations 
- [ ] Determine page type and where it will sit
