### ISSUE TITLE
(UX) Test first iteration of the Carbon Calculator

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#198]
### Summary of task
Look at performance of Carbon Calculator 

### Tasks
- [x] Carry out user testing to find out how users feel about the user journey 
- [ ] Look at ContentSquare to see if users are completing the journey 
- [x]  Are users inspired to make more sustainable choices? 
- [x] Do users understand what their results mean? 
- [x] Can users find the sustainability tips? 
- [x] Can users find hints on the questions? 
- [x] Test 'How many hours will your journey take?' to determine if that's a better way of calculating travel emissions for travel to Scotland 

### Additional context
There may be limited ContentSquare data due to the calculator not being live (live 25/09 onwards)
