### ISSUE TITLE
(SPRINT GOAL) Carbon Calculator - Results

### ISSUE THREAD

**Issue by MichaelGrahamVS** [visitscotland/dot-com-brxm#37]
**As** a visitor to Scotland
**I want** to be able to see the results of my carbon quiz
**So that** I am aware of the impact of my travel choices and can have swaps suggested to me

**Requirements**

- Show result (need to determine if we show if kgs or tonnes) - **Decision is KGs**
- Give equivalent (e.g., this is like riding the West Highland Line 142 times!)
- Give breakdown of result
- Offer suggestions of how to have a more climate-conscious holiday (this may include swapping certain choices, e.g., have you considered switching to a pescatarian diet to try out Scotland's great seafood?)
- Showcase eco-conscious businesses

**Success Criteria**

- The calculator accurately calculates the overall carbon emissions of the trip
- The copy makes the result and suggestions clear
- Sustainable businesses are showcased 
- The copy comes across as helpful and non-judgemental
- The layout makes sense to the user and provides a clear experience
- The design supports the copy
- The design engages the user
- The calculator shows which question the user is on (four of four)

**Nice to have**

Ability to share result on social media
The visitor is assigned a carbon category (e.g., carbon unicorn)

**Tasks**

- [x] how to display the results in chart form- bar chart, pie chart?
- [x] is there any imagery required?
- [x] What are the equivalents?
- [x] Who needs to approve the equivalents - team decision with input from Tiomoid (animals? driving distance? cups of tea?
- [x] content for each equivalent - may not include in this iteration
- [x] content for which tips to display and link to pages
- [x] new component - for displaying results in new form
- [x] test prototype
- [x] ensure accessibility is good
- [x] write acceptance criteria
- [x] integration
- [x] remove Product search widget
- [x] test individual components in component library
- [x] Complete test in feature environment
- [x] document new component behaviour across devices and interactions (confluence)

Original Jira ticket
https://jira.visitscotland.com/browse/VSD-528
