### ISSUE TITLE
(SPRINT GOAL) Map Improvements - Search function

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#75]
**Main Task** 
Determine if users would want a search function on maps 

**Acceptance Criteria** 
- User testing has been carried out on the main maps to find out if users would like a search box to find a city, town, region, island on maps 
- Results have been written up and shared
- If it is found that we should develop this feature, a follow-up ticket should be created 

**Tasks** 

- [x] Design to find or create wireframes of this to be tested https://xd.adobe.com/view/6396e58d-2556-4116-bae0-49335e42de0d-36c5/?x_product=xd-jiraserver%2F1.0
- [ ] Carry out user testing 
- [ ] Design and UX to work together on wireframes 

**Useful Information** 
- The search is not free-form but rather offers a pre-set list of places, regions, islands, towns and cities. Therefore there is no possibility to get 0 results.  TBC by Dev how the search will work (if we go ahead with this) 
- The map will automatically move to the location  and highlight the place from the search results at the same zoom level
- CMS maps are easier as all the information is already there
