### ISSUE TITLE
Map Improvements - Accessibility

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#77]
**Main Task** 
Explore how we can improve the accessibility of our maps 

**Success Criteria** 
- Main map (https://www.visitscotland.com/places-to-go) has been reviewed to ensure they meet D1 accessibility requirements 
- Findings and limitations have been written up and explained in Confluence 
- Clear determination of what level of accessibility can be achieved is explained, and further actions outlined 

**Tasks** 

- [ ] Investigate a no-js version of maps - If no JS what data can be used to provide some functionality in tems of CMS data and DMS data. Should the curated list be displayed without the map? Can information on left still be accessed? 
- [ ] Review Zoonou tests to identify issues 
- [ ] Review icons and colour contrast - some colours are not in the current .com palette, so hands may be tied regarding current palette. Could do investigate work for post-brand alignment (Design and Accessibility to liaise on this) 
- [ ] List of what can be fixed for screen-readers 
- [ ] Explore if we can loop people into the maps (UX and Accessibility to liaise on this) 
- [ ] Explore how left-side navigation can help users using screen readers 
- [ ] UX and FED Wildcat/Puffin chat to ensure work is not duplicated or that work is not reverted back - information passing session
