### ISSUE TITLE
(SE) Map testing - ongoing task

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#79]
**Main Task** 
Unit tests for our code to make sure it is working and future changes do not break previous functionality. We also need them as part of the D1.

**Acceptance Criteria** 

**Tasks** 

- [ ] Map Service Testing - Ticket for back-end testing for the Map service that build different Json to be consumed by the front end team
- [ ] Map module integration with pages testing:
- Ticket for back-end testing for the new CMS module to build a map and the use of the map depending of the page is a General or a Destination page
-The module belongs to a General page - only accept 1 taxonomy and this taxonomy must have children nodes.
- The module belongs to a Destination page - can't have taxonomies selected  as for destination the solution includes DMS categories automatically 
- [ ] Map factory testing: 
- Filters are building.
- The implementation for main maps with and without featured pins
- The implementation for city maps with and without featured pins
- The implementation for region maps with and without featured pins
- The implementation for bespoke maps (for now only iCentres)
