### ISSUE TITLE
(Content/UX) Ability to override link title on internal links

### ISSUE THREAD

**Issue by KirstyScott** [visitscotland/dot-com-brxm#82]
- [ ] **Main Task** 

Currently, internal link CTAs have to be the title of the page they link to. Would like the ability to customise the CTA wording. 

**Context** 
UX recommendations for the iCentre page found that, users were getting confused by CTA wording: 
Under the 'Pick up local leaflets and maps' section of the iCentre page, there is a link titled 'Places to go'. This takes users to the map of Scotland which is not initially clear from the wording. 
Change wording on iCentre 'Map of Scotland' link to 'View our map of Scotland

**Tasks** 
First 
- [ ] Initial investigation with Content into the issue and the possible solutions. Nikki thinks this would require a new field to be added across the CMS, which would mean quite a lot of work to update all the existing pages. 
- [ ] Determine how often this functionality would be needed (discussion with Content and UX) - if once or twice there is a simple way, but if very often then there will be larger implications 

If adding functionality 

- [ ] Create functionality as a shared link on CMS 
- [ ] Could add folder to track where this is needed - if growing, we can make decision to add the field
